from .wan2_1_latent_Resizer_nodes import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_21,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_21,
)
from .wan2_2_latent_Resizer_nodes import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_22,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_22,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_21)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_22)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_21)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_22)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
